spring:
  datasource:
#    url: jdbc:mariadb://capstone.cmwlrea0pvtl.ap-northeast-2.rds.amazonaws.com:3306/mydb
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
#    username: prince
    password: wlgns1204
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:h2:tcp://localhost/~/capstone
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver


  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    #properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIAS2BFGUMTTWUS47UP
      secret-key: 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
    s3:
      bucket: capstone-image
      url: https://s3.ap-northeast-2.amazonaws.com/capstone-image/

app:
  upload:
    dir: C:\Users\KJH\Documents\Capstone\Backend-master\image
#    dir: D:\Capstone\Image\