spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    #url: jdbc:h2:tcp://localhost/~/capstone
    #username: sa
    #password:
    #driver-class-name: org.h2.Driver
    username: root
    password: "wlgns1204"
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    #properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

app:
  upload:
    dir: D:\Capstone\Image\

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  # 특정 문자열 Base64로 인코딩한 값이다
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400